# Generated by Django 6.1.1 on 2026-09-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="ai_category",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="todo",
            name="ai_confidence",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="todo",
            name="ai_priority",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
